sistemaVentasWeb/main/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

app_name = "main"
urlpatterns = [
    path('',views.login_view,name="login_view"),
    path('home/',views.home,name='home'),
    path('logout',views.logout_view,name="logout")
]

sistemaVentasWeb/sistemaVentasWeb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'), name="main"),
    path('',include('usuarios.urls'),name="usuarios"),
    path('',include('productos.urls'),name="productos"),
    path('',include('categorias.urls'),name="categorias"),
    path('',include('proveedores.urls'),name="proveedores")
]

sistemaVentasWeb/usuarios/urls.py
from django.contrib import admin
from django.urls import path
from .views import usuarios_View,create_user_view, update_user_view, delete_user_view
from django.contrib.auth.decorators import login_required
from . import views


app_name = "usuarios"
urlpatterns = [
    path('usuarios/',login_required(usuarios_View.as_view(),login_url="/"),name="usurios_view"),
    path('nuevo-usuario/',login_required(create_user_view.as_view(),login_url="/"),name="create_new_user"),
    path('update-usuario/<int:pk>/',login_required(update_user_view.as_view(),login_url="/"),name="update_user"),
    path('delete-usuario/<int:pk>/',login_required(delete_user_view.as_view(),login_url="/"),name="delete_user")
]

sistemaVentasWeb/usuarios/models.py
from django.db import models

# Create your models here.

sistemaVentasWeb/usuarios/forms.py
from django import forms
from main.models import User

class UsuariosForm(forms.ModelForm):
    
    class Meta:
        model = User        
        fields = ('first_name','last_name','email','role')     
        labels = {'first_name':'Nombre','last_name':'Apellido','email':'Email','role':'Rol'}
        widgets = {
            'first_name':forms.TextInput(attrs={'class':'form-control','placeholder':'Nombre'}),
            'last_name': forms.TextInput(attrs={'class':'form-control','placeholder':'Apellido'}),
            'email':forms.EmailInput(attrs={'class':'form-control','placeholder':'Email'}) ,
            'role':forms.Select(attrs={'class':'form-control'}),
        }

sistemaVentasWeb/usuarios/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from main.models import User
from django.urls import reverse_lazy

from .forms import UsuariosForm

# Create your views here.

class usuarios_View(ListView):
    template_name='usuarios/usuarios.html'
    model = User
    

class create_user_view(CreateView):
    template_name='usuarios/form-user.html'
    form_class = UsuariosForm
    model = User
    success_url=reverse_lazy('usuarios:usurios_view')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['gestion'] = 'new'
        return context
    
class update_user_view(UpdateView):
    template_name='usuarios/form-user.html'
    form_class = UsuariosForm
    model = User
    success_url=reverse_lazy('usuarios:usurios_view')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['gestion'] = 'edit'
        return context
    
class delete_user_view(DeleteView):
    template_name='usuarios/form-user.html'
    model = User
    success_url=reverse_lazy('usuarios:usurios_view')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['gestion'] = 'trash'
        return context

sistemaVentasWeb/usuarios/templates/usuarios/form-user.html
{% extends 'base/base.html' %}
{% block title %}Gestion usuarios{% endblock %}
{% block main %}
<div style="padding:50px;">
    {% if gestion == 'trash' %}
        <form method='POST'>
            <!-- Security token -->
            {% csrf_token %}
            <h1>¿Deséa eliminar al usuario {{object.first_name}} {{object.last_name}}?</h1>
            <ul>
                <li><strong>Nombre:</strong> {{object.first_name}}</li>
                <li><strong>Apellido:</strong> {{object.last_name}}</li>
                <li><strong>Email:</strong> {{object.email}}</li>
                <li><strong>Rol:</strong> {{object.role}}</li>
            </ul>
            <a name="" id="" class="btn btn-primary" href="{% url 'usuarios:usurios_view' %}" role="button">
                <i class="fa fa-ban"></i> Cancelar</a>
            <button class="btn btn-danger" type="submit"><i class="fa-solid fa-trash"></i> Eliminar</button>
        </form>
    {% else %}
        <div class="container" style="text-align:center; width:50%; border:3px solid #184B88; border-radius: 20px">
            <div class="form-group" style="padding:20px">
                <form method="POST">
                    <!-- Security token -->
                    {% csrf_token %}
                    <!-- Using the formset -->
                    {% if gestion == 'new' %}
                        <h1>Nuevo Usuario</h1>
                    {% else %}
                        <h1>Editar Usuario</h1>
                    {% endif %}
                    <div class="row" style="text-align:left;">
                        <div class="col">
                            {{ form.as_p }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <a name="" id="" class="btn btn-danger" href="{% url 'usuarios:usurios_view' %}" 
                            role="button"  style="width:100%">
                                <i class="fa fa-arrow-left"></i> Volver</a>
                        </div>
                        <div class="col">
                            <button class="btn btn-success" type="submit" style="width:100%">
                                <i class="fa-solid fa-floppy-disk"></i> Guardar</button>
                        </div>
                    </div>              
                </form>
            </div> <!-- FORM GROUP -->
        </div> <!-- CONTAINER -->
    {% endif %}
</div> <!-- STYLE PADDING -->

{% endblock %}

sistemaVentasWeb/usuarios/templates/usuarios/usuarios.html
{% extends 'base/tablebase.html' %}
{% block title %}Usuarios{% endblock %}

{% block main %}

    <div class="container-fluid px-4">
        <h1 class="mt-4">Usuarios</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Dashboard</li>
        </ol>
        
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                Listado de Usuarios
            </div>
            
            <div class="card-body">


                <table id="example" class="display compact" style="width:100%">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Email</th>
                            <th>Rol</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if object_list %}
                            {% for us in object_list  %}
                                {% if us.id != user.id %}
                                    <tr>
                                        <td>{{us.id}}</td>
                                        <td>{{us.first_name}}</td>
                                        <td>{{us.last_name}}</td>
                                        <td>{{us.email}}</td>
                                        <td>{{us.role}}</td>
                                        <td>
                                            <a name="" id="" class="btn btn-warning" href="{% url 'usuarios:update_user' us.id %}" role="button">
                                                <i class="fa fa-edit"></i></a>
                                            <a name="" id="" class="btn btn-danger" href="{% url 'usuarios:delete_user' us.id %}" role="button">
                                                <i class="fa fa-trash"></i></a>
                                        </td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </tbody>
                </table>
            </div>
            
        </div>
        <a name="" id="" class="btn btn-danger" href="{% url 'main:home' %}" role="button">
            <i class="fa fa-home"></i> Volver</a>
        <a name="" id="" class="btn btn-success" href="{% url 'usuarios:create_new_user' %}" role="button">
            <i class="fa fa-add"></i> Nuevo Usuario</a>
    </div>


{% endblock %}