sistemaVentasWeb/categorias/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required
from . import views

app_name = "categorias"
urlpatterns = [
    path('categorias/',login_required(Categories_view.as_view(),login_url="/"),name="categories_view"),
    path('nueva-categoria/',login_required(create_category_view.as_view(),login_url="/"),name="create_new_category"),
    path('update-categoria/<int:pk>/',login_required(update_category_view.as_view(),login_url="/"),name="update_category"),
    path('delete-categoria/<int:pk>/',login_required(delete_category_view.as_view(),login_url="/"),name="delete_category"),
    path('detail-categoria/<int:id>/',login_required(views.detail_category_view,login_url="/"),name="detail_category"),
    
]

sistemaVentasWeb/main/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

app_name = "main"
urlpatterns = [
    path('',views.login_view,name="login_view"),
    path('home/',views.home,name='home'),
    path('logout',views.logout_view,name="logout")
]

sistemaVentasWeb/productos/urls.py
from django.contrib import admin
from django.urls import path
#from .views import products_view,create_product_view, update_products_view, delete_products_view
from .views import *
from django.contrib.auth.decorators import login_required
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = "productos"
urlpatterns = [
    path('productos/',login_required(products_view.as_view(),login_url="/"),name="products_view"),
    path('nuevo-producto/',login_required(create_product_view.as_view(),login_url="/"),name="create_new_product"),
    path('update-producto/<int:pk>/',login_required(update_product_view.as_view(),login_url="/"),name="update_product"),
    path('delete-producto/<int:pk>/',login_required(delete_product_view.as_view(),login_url="/"),name="delete_product"),
    path('detail-producto/<int:pk>/',login_required(detail_product_view.as_view(),login_url="/"),name="detail_product"),

    
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

sistemaVentasWeb/sistemaVentasWeb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'), name="main"),
    path('',include('usuarios.urls'),name="usuarios"),
    path('',include('productos.urls'),name="productos"),
    path('',include('categorias.urls'),name="categorias"),
    path('',include('proveedores.urls'),name="proveedores")
]

sistemaVentasWeb/categorias/models.py
from django.db import models

# Create your models here.
class category(models.Model):
    name_category = models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name="Category"
        verbose_name_plural="Categories"
        
    def __str__(self):
        return self.name_category

sistemaVentasWeb/productos/models.py
from django.db import models
from categorias.models import category
# Create your models here.

class Product(models.Model):
    code = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255)
    description = models.TextField()
    stock = models.IntegerField(default=0)
    image = models.ImageField(upload_to='products/', null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    category_product = models.ForeignKey(category,on_delete=models.CASCADE)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name="Product"
        verbose_name_plural="Products"

sistemaVentasWeb/categorias/forms.py
from django import forms
from .models import category

class CategoryForm(forms.ModelForm):
    
    class Meta:
        model = category        
        fields = ('name_category',)     
        labels = {'name_category':'Categoría'}
        widgets = {
            'name_category': forms.TextInput(attrs={'class':'form-control','placeholder':'Nombre Categoría'})  
        }

sistemaVentasWeb/productos/forms.py
from django import forms
from .models import Product

class ProductosForm(forms.ModelForm):
    
    class Meta:
        model = Product        
        fields = ('code','name','description','image','stock','price','available','category_product')     
        labels = {'code':'Codigo','name':'Producto','description':'Descripción','stock':'Stock',
                  'image':'Imagen','price':'Precio','available':'Disponibilidad',
                  'category_product':'Categoría'}
        widgets = {
            'code':forms.TextInput(attrs={'class':'form-control','placeholder':'Codigo'}),
            'name': forms.TextInput(attrs={'class':'form-control','placeholder':'Producto'}),
            'description':forms.Textarea(attrs={'class':'form-control','placeholder':'Descripción'}) ,
            'stock':forms.NumberInput(attrs={'class':'form-control','placeholder':'stock','type':'number'}) ,
            'image':forms.ClearableFileInput(attrs={'class':'img-thumbnail'}),
            'price':forms.NumberInput(attrs={'class':'form-control','placeholder':'precio'}) ,
            'category_product':forms.Select(attrs={'class':'form-control'}),
            'available':forms.CheckboxInput(attrs={'class':'form-check-input','type':'checkbox'}) 
        }
        

sistemaVentasWeb/categorias/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from categorias.models import category
from categorias.forms import CategoryForm
from productos.models import Product
from django.views.generic import ListView,CreateView,UpdateView,DeleteView

# Create your views here.
class Categories_view(ListView):
    template_name='categorias/categorias.html'
    model = category
    

class create_category_view(CreateView):
    template_name='categorias/form-category.html'
    form_class = CategoryForm
    model = category
    success_url=reverse_lazy('categorias:categories_view')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['gestion'] = 'new'
        return context
    
class update_category_view(UpdateView):
    template_name='categorias/form-category.html'
    form_class = CategoryForm
    model = category
    success_url=reverse_lazy('categorias:categories_view')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['gestion'] = 'edit'
        return context
    
class delete_category_view(DeleteView):
    template_name='categorias/form-category.html'
    model = category
    success_url=reverse_lazy('categorias:categories_view')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['gestion'] = 'trash'
        return context
    
def detail_category_view(request,id):
    context = {}
    listado_productos = Product.objects.filter(category_product=id)
    categ = category.objects.filter(pk=id).first()
    context['gestion'] = 'detail'
    context['categ'] = categ
    context['listado_productos'] = listado_productos
    #category_name = get_object_or_404(category, pk=id)
    #quantity_products = category_name.producto_set.count()
    return render(request,'categorias/form-category.html',context=context)

sistemaVentasWeb/productos/views.py
from django.views.generic import ListView,CreateView,UpdateView,DeleteView,DetailView
from .models import Product
from .forms import ProductosForm
from django.urls import reverse_lazy

# Create your views here.

class products_view(ListView):
    template_name='productos/productos.html'
    model = Product

class create_product_view(CreateView):
    template_name='productos/form-product.html'
    form_class = ProductosForm
    model = Product
    success_url=reverse_lazy('productos:products_view')
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['gestion'] = 'new'
        return context

class update_product_view(UpdateView):
    template_name='productos/form-product.html'
    form_class = ProductosForm
    model = Product
    success_url=reverse_lazy('productos:products_view')
    
    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context['gestion'] = 'edit'
            return context  

class delete_product_view(DeleteView):
    template_name='productos/form-product.html'
    model = Product
    success_url=reverse_lazy('productos:products_view')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['gestion'] = 'trash'
        return context

class detail_product_view(DetailView):
    template_name='productos/form-product.html'
    model = Product
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['gestion'] = 'detail'
        return context

sistemaVentasWeb/productos/templates/categorias/categorias.html
{% extends 'base/tablebase.html' %}
{% block title %}Categorías{% endblock %}

{% block main %}

    <div class="container-fluid px-4">
        <h1 class="mt-4">Categorías</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Dashboard</li>
        </ol>
        
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                Listado de Categorías
            </div>
            
            <div class="card-body">


                <table id="example" class="display compact" style="width:100%">
                    <thead>
                        <tr>
                            <th>id</th>
                            <th>Categoría</th>
                            <th>created</th>
                            <th>updated</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if object_list %}
                            {% for categ in object_list  %}
                               
                                <tr>
                                    <td>{{categ.id}}</td>
                                    <td>{{categ.name_category}}</td>
                                    <td>{{categ.created}}</td>
                                    <td>{{categ.updated}}</td>
                                    <td>
                                        <a name="" id="" class="btn btn-info" href="#" 
                                        role="button">
                                            <i class="fa fa-circle-info"></i></a>
                                        <a name="" id="" class="btn btn-warning" href="{% url 'productos:update_category' categ.id %}" 
                                        role="button">
                                            <i class="fa fa-edit"></i></a>
                                        <a name="" id="" class="btn btn-danger" href="{% url 'productos:delete_category' categ.id %}" 
                                        role="button">
                                            <i class="fa fa-trash"></i></a>
                                    </td>
                                </tr>
                               
                            {% endfor %}
                        {% endif %}
                    </tbody>
                </table>
            </div>
            
        </div>
        <a name="" id="" class="btn btn-danger" href="{% url 'productos:products_view' %}" role="button">
            <i class="fa fa-arrow-left"></i> Volver</a>
        <a name="" id="" class="btn btn-success" href="{% url 'productos:create_new_category' %}" role="button">
            <i class="fa fa-add"></i> Nueva Categoría</a>
        <a name="" id="" class="btn btn-dark" href="#" role="button">
            <i class="fa fa-money-check"></i> Ver Proveedores</a>
    </div>


{% endblock %}

sistemaVentasWeb/productos/templates/categorias/form-category.html
{% extends 'base/base.html' %}
{% block title %}Gestion Categorías{% endblock %}
{% block main %}
<div style="padding:50px;">
    {% if gestion == 'trash' %}
        <form method='POST'>
            <!-- Security token -->
            {% csrf_token %}
            <h1>¿Deséa eliminar categoría {{object.name_category}}?</h1>
            <ul>
                <li><strong>Ultima Actualización:</strong> {{object.updated}}</li>
                <li><strong>Fecha de creación:</strong> {{object.created}}</li>
            </ul>
            <a name="" id="" class="btn btn-primary" href="{% url 'productos:categories_view' %}" role="button">
                <i class="fa fa-ban"></i> Cancelar</a>
            <button class="btn btn-danger" type="submit"><i class="fa-solid fa-trash"></i> Eliminar</button>
        </form>
    {% else %}
        <div class="container" style="text-align:center; width:50%; border:3px solid #184B88; border-radius: 20px">
            <div class="form-group" style="padding:20px">
                <form method="POST">
                    <!-- Security token -->
                    {% csrf_token %}
                    <!-- Using the formset -->
                    {% if gestion == 'new' %}
                        <h1>Nueva Categoría</h1>
                    {% else %}
                        <h1>Editar Categoría</h1>
                    {% endif %}
                    <div class="row" style="text-align:left;">
                        <div class="col">
                            {{ form.as_p }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <a name="" id="" class="btn btn-danger" href="{% url 'productos:categories_view' %}" 
                            role="button"  style="width:100%">
                                <i class="fa fa-arrow-left"></i> Volver</a>
                        </div>
                        <div class="col">
                            <button class="btn btn-success" type="submit" style="width:100%">
                                <i class="fa-solid fa-floppy-disk"></i> Guardar</button>
                        </div>
                    </div>              
                </form>
            </div> <!-- FORM GROUP -->
        </div> <!-- CONTAINER -->
    {% endif %}
</div> <!-- STYLE PADDING -->

{% endblock %}