sistemaVentasWeb/categorias/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required
from . import views

app_name = "categorias"
urlpatterns = [
    path('categorias/',login_required(Categories_view.as_view(),login_url="/"),name="categories_view"),
    path('nueva-categoria/',login_required(create_category_view.as_view(),login_url="/"),name="create_new_category"),
    path('update-categoria/<int:pk>/',login_required(update_category_view.as_view(),login_url="/"),name="update_category"),
    path('delete-categoria/<int:pk>/',login_required(delete_category_view.as_view(),login_url="/"),name="delete_category"),
    path('detail-categoria/<int:id>/',login_required(views.detail_category_view,login_url="/"),name="detail_category"),
    
]

sistemaVentasWeb/main/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

app_name = "main"
urlpatterns = [
    path('',views.login_view,name="login_view"),
    path('home/',views.home,name='home'),
    path('logout',views.logout_view,name="logout")
]

sistemaVentasWeb/productos/urls.py
from django.contrib import admin
from django.urls import path
#from .views import products_view,create_product_view, update_products_view, delete_products_view
from .views import *
from django.contrib.auth.decorators import login_required
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = "productos"
urlpatterns = [
    path('productos/',login_required(products_view.as_view(),login_url="/"),name="products_view"),
    path('nuevo-producto/',login_required(create_product_view.as_view(),login_url="/"),name="create_new_product"),
    path('update-producto/<int:pk>/',login_required(update_product_view.as_view(),login_url="/"),name="update_product"),
    path('delete-producto/<int:pk>/',login_required(delete_product_view.as_view(),login_url="/"),name="delete_product"),
    path('detail-producto/<int:pk>/',login_required(detail_product_view.as_view(),login_url="/"),name="detail_product"),

    
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

sistemaVentasWeb/sistemaVentasWeb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'), name="main"),
    path('',include('usuarios.urls'),name="usuarios"),
    path('',include('productos.urls'),name="productos"),
    path('',include('categorias.urls'),name="categorias"),
    path('',include('proveedores.urls'),name="proveedores")
]

sistemaVentasWeb/productos/models.py
from django.db import models
from categorias.models import category
# Create your models here.

class Product(models.Model):
    code = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255)
    description = models.TextField()
    stock = models.IntegerField(default=0)
    image = models.ImageField(upload_to='products/', null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    category_product = models.ForeignKey(category,on_delete=models.CASCADE)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name="Product"
        verbose_name_plural="Products"

sistemaVentasWeb/productos/forms.py
from django import forms
from .models import Product

class ProductosForm(forms.ModelForm):
    
    class Meta:
        model = Product        
        fields = ('code','name','description','image','stock','price','available','category_product')     
        labels = {'code':'Codigo','name':'Producto','description':'Descripción','stock':'Stock',
                  'image':'Imagen','price':'Precio','available':'Disponibilidad',
                  'category_product':'Categoría'}
        widgets = {
            'code':forms.TextInput(attrs={'class':'form-control','placeholder':'Codigo'}),
            'name': forms.TextInput(attrs={'class':'form-control','placeholder':'Producto'}),
            'description':forms.Textarea(attrs={'class':'form-control','placeholder':'Descripción'}) ,
            'stock':forms.NumberInput(attrs={'class':'form-control','placeholder':'stock','type':'number'}) ,
            'image':forms.ClearableFileInput(attrs={'class':'img-thumbnail'}),
            'price':forms.NumberInput(attrs={'class':'form-control','placeholder':'precio'}) ,
            'category_product':forms.Select(attrs={'class':'form-control'}),
            'available':forms.CheckboxInput(attrs={'class':'form-check-input','type':'checkbox'}) 
        }
        

sistemaVentasWeb/productos/views.py
from django.views.generic import ListView,CreateView,UpdateView,DeleteView,DetailView
from .models import Product
from .forms import ProductosForm
from django.urls import reverse_lazy

# Create your views here.

class products_view(ListView):
    template_name='productos/productos.html'
    model = Product

class create_product_view(CreateView):
    template_name='productos/form-product.html'
    form_class = ProductosForm
    model = Product
    success_url=reverse_lazy('productos:products_view')
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['gestion'] = 'new'
        return context

class update_product_view(UpdateView):
    template_name='productos/form-product.html'
    form_class = ProductosForm
    model = Product
    success_url=reverse_lazy('productos:products_view')
    
    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context['gestion'] = 'edit'
            return context  

class delete_product_view(DeleteView):
    template_name='productos/form-product.html'
    model = Product
    success_url=reverse_lazy('productos:products_view')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['gestion'] = 'trash'
        return context

class detail_product_view(DetailView):
    template_name='productos/form-product.html'
    model = Product
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['gestion'] = 'detail'
        return context

sistemaVentasWeb/productos/templates/productos/form-product.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Gestion Productos{% endblock %}
{% block main %}
<div style="padding:50px;">
    {% if gestion == 'trash' %}
        <form method='POST'>
            <!-- Security token -->
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <h1>¿Deséa eliminar el producto {{object.name}}?</h1>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <img src="{{ object.image.url }}" class="img-thumbnail">
                </div>
                <div class="col">
                    <ul>
                        <li><strong>Código:</strong> {{object.code}}</li>
                        <li><strong>Nombre:</strong> {{object.name}}</li>
                        <li><strong>Descripción:</strong> {{object.description}}</li>
                        <li><strong>Stock:</strong> {{object.stock}}</li>
                        <li><strong>Precio: </strong> ${{object.price}}</li>
                        <li><strong>Categoría:</strong> {{object.category_product}}</li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <a name="" id="" class="btn btn-primary" href="javascript: history.go(-1)"
                     role="button" style="width:100%">
                        <i class="fa fa-ban"></i> Cancelar</a>
                </div>
                <div class="col">
                    <button class="btn btn-danger" type="submit" style="width:100%"><i class="fa-solid fa-trash">
                    </i> Eliminar</button>
                </div>
            </div>
            
        </form>
    {% else %}
        <!-- <div class="container" style="text-align:center; width:95%; border:3px solid #184B88; border-radius: 20px"> -->
        <div class="container containerFormBorder">
            <div class="form-group" style="padding:20px">
                <form method="POST" enctype="multipart/form-data">
                    <!-- Security token -->
                    {% csrf_token %}
                    <!-- Using the formset -->
                    <div class="row" style="text-align:center;">
                        <div class="col">
                            {% if gestion == 'new' %}
                                <h1>Nuevo Producto</h1>
                            {% elif gestion == 'edit' %}
                                <h1>Editar Producto</h1>
                            {% else %}
                                <h1>{{ object.name }}</h1>
                            {% endif %}
                        </div>
                    </div>
                    
                    <div class="row" style="text-align:left;">
                        <div class="col">
                            {% if gestion == 'detail' %}
                                <div class="row">
                                    <div class="col">
                                        {% if object.image.url %}
                                            <img src="{{ object.image.url }}" class="img-thumbnail">
                                        {% else %}
                                             <img src="{% static 'images/default.jpg' %}" class="img-thumbnail">
                                        {% endif %}
                                    </div>
                                    <div class="col">
                                        <p><strong>Código:</strong> {{ object.code }}</p>
                                        <p><strong>Descripción:</strong> {{ object.description }}</p>
                                        <p><strong>Stock:</strong> 
                                            {% if object.stock <= 3 %}
                                                <span style="color:red;">{{ object.stock }}</span>
                                            {% else %}
                                                {{ object.stock }}
                                            {% endif %}
                                        </p>
                                        <p><strong>Precio:</strong> ${{ object.price }}</p>
                                        <p><strong>Estado:</strong> 
                                            {% if object.available %}
                                                <span style="color:green; font-weight: bold;">ACTIVO</span>
                                            {% else %}
                                                <span style="color:red; font-weight: bold;">NO ACTIVO</span>
                                            {% endif %}
                                        </p>
                                        <p><strong>Categoría:</strong> {{ object.category_product }}</p>
                                        <p><strong>Creado:</strong> {{ object.created|date:"d/m/Y H:i:s" }}</p>
                                        <p><strong>Actualizado:</strong> {{ object.updated|date:"d/m/Y H:i:s" }}</p>
                                    </div>
                                </div>
                                
                            {% else %}
                                {{ form.as_p }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <a name="" id="" class="btn btn-danger" href="javascript: history.go(-1)" 
                            role="button"  style="width:100%">
                                <i class="fa fa-arrow-left"></i> Volver</a>
                        </div>
                        {% if gestion == 'detail' %}
                            <div class="col">
                                <a name="" id="" class="btn btn-warning" href="{% url 'productos:update_product' object.code %}" 
                                role="button"  style="width:100%">
                                    <i class="fa fa-edit"></i>Editar</a>
                            </div>
                        {% else %}
                            <div class="col">
                                <button class="btn btn-success" type="submit" style="width:100%">
                                    <i class="fa-solid fa-floppy-disk"></i> Guardar</button>
                            </div>
                        {% endif %}
                    </div>              
                </form>
            </div> <!-- FORM GROUP -->
        </div> <!-- CONTAINER -->
    {% endif %}
</div> <!-- STYLE PADDING -->

{% endblock %}

sistemaVentasWeb/productos/templates/productos/productos.html
{% extends 'base/tablebase.html' %}
{% block title %}Productos{% endblock %}

{% block main %}

    <div class="container-fluid px-4">
        <h1 class="mt-4">Productos</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Dashboard</li>
        </ol>
        
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                Listado de Productos
            </div>
            
            <div class="card-body">


                <table id="example" class="display compact" style="width:100%">
                    <thead>
                        <tr>
                            <th>Cod.</th>
                            <th>Nombre</th>
                            <th>Precio</th>
                            <th>Stock</th>
                            <th>Categoria</th>
                            <th>Estado</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if object_list %}
                            {% for prod in object_list  %}
                               
                                <tr>
                                    <td>{{prod.code}}</td>
                                    <td>{{prod.name}}</td>
                                    <td>${{prod.price}}</td>
                                    <td>
                                        {% if prod.stock <= 3 %}
                                        <span style="color:red;">{{prod.stock}}</span>
                                        {% else %}
                                            {{prod.stock}}
                                        {% endif %}
                                    </td>
                                    <td>{{prod.category_product}}</td>
                                    {%if prod.available %}
                                        <td><span style="color:green; font-weight: bold;">ACTIVO</span></td>
                                    {% else %}
                                        <td><span style="color:red; font-weight: bold;">NO ACTIVO</span></td>
                                    {% endif %}
                                    <td>
                                        <a name="" id="" class="btn btn-info" href="{% url 'productos:detail_product' prod.code %}" 
                                        role="button">
                                            <i class="fa fa-circle-info"></i></a>
                                        <a name="" id="" class="btn btn-warning" href="{% url 'productos:update_product' prod.code %}" 
                                        role="button">
                                            <i class="fa fa-edit"></i></a>
                                        <a name="" id="" class="btn btn-danger" href="{% url 'productos:delete_product' prod.code %}" 
                                        role="button">
                                            <i class="fa fa-trash"></i></a>
                                    </td>
                                </tr>
                               
                            {% endfor %}
                        {% endif %}
                    </tbody>
                </table>
            </div>
            
        </div>
        <a name="" id="" class="btn btn-danger" href="javascript: history.go(-1)" role="button">
            <i class="fa fa-home"></i> Volver</a>
        <a name="" id="" class="btn btn-success" href="{% url 'productos:create_new_product' %}" role="button">
            <i class="fa fa-add"></i> Nuevo Producto</a>
        <a name="" id="" class="btn btn-primary" href="{% url 'categorias:categories_view' %}" role="button">
            <i class="fa fa-list"></i> Ver Categorías</a>
        <a name="" id="" class="btn btn-dark" href="#" role="button">
            <i class="fa fa-credit-card"></i> Comprar a proveedor</a>
    </div>


{% endblock %}