sistemaVentasWeb/categorias/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required
from . import views

app_name = "categorias"
urlpatterns = [
    path('categorias/',login_required(Categories_view.as_view(),login_url="/"),name="categories_view"),
    path('nueva-categoria/',login_required(create_category_view.as_view(),login_url="/"),name="create_new_category"),
    path('update-categoria/<int:pk>/',login_required(update_category_view.as_view(),login_url="/"),name="update_category"),
    path('delete-categoria/<int:pk>/',login_required(delete_category_view.as_view(),login_url="/"),name="delete_category"),
    path('detail-categoria/<int:id>/',login_required(views.detail_category_view,login_url="/"),name="detail_category"),
    
]

sistemaVentasWeb/main/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

app_name = "main"
urlpatterns = [
    path('',views.login_view,name="login_view"),
    path('home/',views.home,name='home'),
    path('logout',views.logout_view,name="logout")
]

sistemaVentasWeb/productos/urls.py
from django.contrib import admin
from django.urls import path
#from .views import products_view,create_product_view, update_products_view, delete_products_view
from .views import *
from django.contrib.auth.decorators import login_required
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = "productos"
urlpatterns = [
    path('productos/',login_required(products_view.as_view(),login_url="/"),name="products_view"),
    path('nuevo-producto/',login_required(create_product_view.as_view(),login_url="/"),name="create_new_product"),
    path('update-producto/<int:pk>/',login_required(update_product_view.as_view(),login_url="/"),name="update_product"),
    path('delete-producto/<int:pk>/',login_required(delete_product_view.as_view(),login_url="/"),name="delete_product"),
    path('detail-producto/<int:pk>/',login_required(detail_product_view.as_view(),login_url="/"),name="detail_product"),

    
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

sistemaVentasWeb/proveedores/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required
from . import views

app_name = "proveedores"
urlpatterns = [
  path('proveedores/',login_required(providers_view.as_view(),login_url='/'),name='providers_view'),
  path('nuevo-proveedor/',login_required(create_providers_view.as_view(),login_url="/"),name="create_new_provider"),
]

sistemaVentasWeb/sistemaVentasWeb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'), name="main"),
    path('',include('usuarios.urls'),name="usuarios"),
    path('',include('productos.urls'),name="productos"),
    path('',include('categorias.urls'),name="categorias"),
    path('',include('proveedores.urls'),name="proveedores")
]

sistemaVentasWeb/categorias/models.py
from django.db import models

# Create your models here.
class category(models.Model):
    name_category = models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name="Category"
        verbose_name_plural="Categories"
        
    def __str__(self):
        return self.name_category

sistemaVentasWeb/categorias/forms.py
from django import forms
from .models import category

class CategoryForm(forms.ModelForm):
    
    class Meta:
        model = category        
        fields = ('name_category',)     
        labels = {'name_category':'Categoría'}
        widgets = {
            'name_category': forms.TextInput(attrs={'class':'form-control','placeholder':'Nombre Categoría'})  
        }

sistemaVentasWeb/categorias/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from categorias.models import category
from categorias.forms import CategoryForm
from productos.models import Product
from django.views.generic import ListView,CreateView,UpdateView,DeleteView

# Create your views here.
class Categories_view(ListView):
    template_name='categorias/categorias.html'
    model = category
    

class create_category_view(CreateView):
    template_name='categorias/form-category.html'
    form_class = CategoryForm
    model = category
    success_url=reverse_lazy('categorias:categories_view')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['gestion'] = 'new'
        return context
    
class update_category_view(UpdateView):
    template_name='categorias/form-category.html'
    form_class = CategoryForm
    model = category
    success_url=reverse_lazy('categorias:categories_view')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['gestion'] = 'edit'
        return context
    
class delete_category_view(DeleteView):
    template_name='categorias/form-category.html'
    model = category
    success_url=reverse_lazy('categorias:categories_view')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['gestion'] = 'trash'
        return context
    
def detail_category_view(request,id):
    context = {}
    listado_productos = Product.objects.filter(category_product=id)
    categ = category.objects.filter(pk=id).first()
    context['gestion'] = 'detail'
    context['categ'] = categ
    context['listado_productos'] = listado_productos
    #category_name = get_object_or_404(category, pk=id)
    #quantity_products = category_name.producto_set.count()
    return render(request,'categorias/form-category.html',context=context)

sistemaVentasWeb/categorias/templates/categorias/categorias.html
{% extends 'base/tablebase.html' %}
{% block title %}Categorías{% endblock %}

{% block main %}

    <div class="container-fluid px-4">
        <h1 class="mt-4">Categorías</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Dashboard</li>
        </ol>
        
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                Listado de Categorías
            </div>
            
            <div class="card-body">


                <table id="example" class="display compact" style="width:100%">
                    <thead>
                        <tr>
                            <th>id</th>
                            <th>Categoría</th>
                            <th>created</th>
                            <th>updated</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if object_list %}
                            {% for categ in object_list  %}
                               
                                <tr>
                                    <td>{{categ.id}}</td>
                                    <td>{{categ.name_category}}</td>
                                    <td>{{categ.created|date:"d/m/Y H:i:s"}}</td>
                                    <td>{{categ.updated|date:"d/m/Y H:i:s"}}</td>
                                    <td>
                                        <a name="" id="" class="btn btn-info" href="{% url 'categorias:detail_category' categ.id %}" 
                                        role="button">
                                            <i class="fa fa-circle-info"></i></a>
                                        <a name="" id="" class="btn btn-warning" href="{% url 'categorias:update_category' categ.id %}" 
                                        role="button">
                                            <i class="fa fa-edit"></i></a>
                                        <a name="" id="" class="btn btn-danger" href="{% url 'categorias:delete_category' categ.id %}" 
                                        role="button">
                                            <i class="fa fa-trash"></i></a>
                                    </td>
                                </tr>
                               
                            {% endfor %}
                        {% endif %}
                    </tbody>
                </table>
            </div>
            
        </div>
        <a name="" id="" class="btn btn-danger" href="javascript: history.go(-1)" role="button">
            <i class="fa fa-arrow-left"></i> Volver</a>
        <a name="" id="" class="btn btn-success" href="{% url 'categorias:create_new_category' %}" role="button">
            <i class="fa fa-add"></i> Nueva Categoría</a>
        <a name="" id="" class="btn btn-dark" href="{% url 'proveedores:providers_view' %}" role="button">
            <i class="fa fa-money-check"></i> Ver Proveedores</a>
    </div>


{% endblock %}

sistemaVentasWeb/categorias/templates/categorias/detail-cateogory.html
{% extends 'base/base.html' %}
{% block title %}Gestion Categorías{% endblock %}
{% block main %}


{% endblock %}

sistemaVentasWeb/categorias/templates/categorias/form-category.html
{% extends 'base/base.html' %}
{% block title %}Gestion Categorías{% endblock %}
{% block main %}
<div style="padding:50px;">
    {% if gestion == 'trash' %}
        <form method='POST'>
            <!-- Security token -->
            {% csrf_token %}
            <h1>¿Deséa eliminar categoría {{object.name_category}}?</h1>
            <ul>
                <li><strong>Ultima Actualización:</strong> {{object.updated}}</li>
                <li><strong>Fecha de creación:</strong> {{object.created}}</li>
            </ul>
            <a name="" id="" class="btn btn-primary" href="javascript: history.go(-1)" role="button">
                <i class="fa fa-ban"></i> Cancelar</a>
            <button class="btn btn-danger" type="submit"><i class="fa-solid fa-trash"></i> Eliminar</button>
        </form>
    {% else %}
        <div class="container containerFormBorder">
            <div class="form-group" style="padding:20px">
                <form method="POST">
                    <!-- Security token -->
                    {% csrf_token %}
                    <!-- Using the formset -->
                    {% if gestion == 'new' %}
                        <h1>Nueva Categoría</h1>
                    {% elif getion == 'edit' %}
                        <h1>Editar Categoría</h1>
                    {% else %}
                        <h1>{{ categ.name_category }}</h1>
                    {% endif %}
                    <div class="row" style="text-align:left;">
                        <div class="col">
                            {% if gestion == 'detail' %}
                                <div class="row">
                                    <div class="col">
                                        <ul>
                                            <li><p><strong>Creado:</strong> {{ categ.created|date:"d/m/Y H:i:s" }}</p></li>
                                             
                                            <li><p><strong>Actualizado:</strong> {{ categ.updated|date:"d/m/Y H:i:s" }}</p></li>
                                            
                                            <li><p><strong>Cantidad Productos:</strong> {{ listado_productos|length }}</p></li>

                                        </ul>
                                    </div> <!-- Cierre col 1 -->
                                </div> <!-- Cierre row 1 -->

                                {% if listado_productos %}

                                <div class="row">
                                    <div class="col">
                                        <h2>Productos</h2>
                                    </div ><!-- Cierre col 1 -->
                                </div> <!-- Cierre row 2 -->

                                <div class="row">
                                    <div class="col">
                                        <div class="table-responsive">
                                            <table class="table">
                                                <thead>
                                                    <tr>
                                                        <th scope="col">IMAGEN</th>
                                                        <th scope="col">CODIGO</th>
                                                        <th scope="col">PRODUCTO</th>
                                                        <th scope="col">ACCIONES</th>
                                                    </tr>
                                                </thead>
                                                <tbody style="text-align: left; vertical-align: middle;">
                                                    {% for producto in listado_productos %}
                                                    <tr class="">
                                                        <td style="width: 10%;"><img src="{{ producto.image.url }}" class="card-img-top table-img-products" alt="..."></td>
                                                        <td>{{producto.code}}</td>
                                                        <td>{{producto.name}}</td>
                                                        <td>
                                                            <a name="" id="" class="btn btn-info" href="{% url 'productos:detail_product' producto.code %}" 
                                                            role="button"><i class="fa fa-circle-info"></i> Detalles</a>
                                                        </td>
                                                    </tr>
                                                    {% endfor %}
                                                </tbody>
                                            </table>
                                        </div> <!-- Cierre de table-responsive -->
                                    </div>  <!-- Cierre col 1 -->
                                </div> <!-- Cierre row 3 -->
                                {% endif %}

                            {% else %}
                                {{ form.as_p }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <a name="" id="" class="btn btn-danger" href="javascript: history.go(-1)" 
                            role="button"  style="width:100%">
                                <i class="fa fa-arrow-left"></i> Volver</a>
                        </div>
                        <div class="col">
                            {% if gestion != 'detail'%}
                                <button class="btn btn-success" type="submit" style="width:100%">
                                    <i class="fa-solid fa-floppy-disk"></i> Guardar</button>
                            {% endif %}
                        </div>
                        
                    </div>              
                </form>
            </div> <!-- FORM GROUP -->
        </div> <!-- CONTAINER -->
    {% endif %}
</div> <!-- STYLE PADDING -->

{% endblock %}